"""Constants for the Eldom integration."""

DOMAIN = "eldom"

MANUFACTURER_NAME = "Eldom"

DEVICE_TYPE_FLAT_BOILER_ELDOM = 7
DEVICE_TYPE_SMART_BOILER_ELDOM = 5
DEVICE_TYPE_CONVECTOR_HEATER_ELDOM = 4
DEVICE_TYPE_CONVECTOR_HEATER_IOT_ELDOM = "HTRCNV"
DEVICE_TYPE_FLAT_BOILER_IOT_ELDOM = "BLR2T"

DEVICE_TYPE_MAPPING = {
    # Eldom devices
    DEVICE_TYPE_FLAT_BOILER_ELDOM: "Flat Boiler",
    DEVICE_TYPE_SMART_BOILER_ELDOM: "Smart Boiler",
    DEVICE_TYPE_CONVECTOR_HEATER_ELDOM: "Convector Heater",
    # IoT Eldom devices
    DEVICE_TYPE_CONVECTOR_HEATER_IOT_ELDOM: "Convector Heater",
    DEVICE_TYPE_FLAT_BOILER_IOT_ELDOM: "Flat Boiler",
}

CONF_API = "api"

ELDOM_API = "myeldom"
ELDOM_API_URL = "myeldom.com"
IOT_ELDOM_API = "ioteldom"
IOT_ELDOM_API_URL = "iot.myeldom.com"

API_CHOICES = {
    ELDOM_API: ELDOM_API_URL,
    IOT_ELDOM_API: IOT_ELDOM_API_URL,
}
